### ISSUE TITLE
Day passed instead of year and vice-versa

### ISSUE THREAD

**Issue by prof18** [GDG-Venezia/gdg-venezia-showcase-app-old#2]
https://github.com/GDG-Venezia/gdg-venezia-showcase-app/blob/8358575e46ef573a00b89d38f00b379361a16255/app/src/commonMain/kotlin/com/github/gdgvenezia/data/RepositoryImpl.kt#L14-L16

**Comment by TechIsFun** [comment]
Fixed in develop
